### PR TITLE
Fix/scenarios restructure

### LINKED ISSUE #40: Restructure terraform infra
Reusable modules should be moved to parent dir

### LINKED ISSUE #47: Improve telegraf report for continuous test
Add client hostname or public IP as tag to get additional info on board

### PR DESCRIPTION
**Pull request by outcatcher**
Implement shared modules for scenarios

Resolve #40 

 * [x] scenario 1
 * [x] scenario 2
 * [x] `skeleton.sh`

Fix by @anton-sidelnikov will resolve #47

### CODE REVIEW

**Comment by outcatcher** [comment]
Will be ready for review after adding fix for #47

File: scenarios/destroy.sh [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+scenario_name="$1"
+
+if [[ -z ${scenario_name} ]]; then
+    echo "Scenario name is missing"
+    exit 2
+fi
+
+project_root=$(bash ./core/get_project_root.sh)
+
+# first - build infra
```
Comment (anton-sidelnikov) [inline scenarios/destroy.sh]: strange comment

File: scenarios/modules/bastion/variables.tf [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+variable "router" {}
+variable "volume_bastion" {
+  type    = number
+  default = 10
+}
+
+variable "bastion_local_ip" {
+  default = ""
+}
+variable "nodes_count" {
```
Comment (anton-sidelnikov) [inline scenarios/modules/bastion/variables.tf]: duplicate in scenario1/variables.tf
